/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/Views/**/*.php",
    "./public/**/*.html",
    "./marketplace/**/*.php",
  ],
  theme: {
    extend: {
      colors: {
        // Organic Lattice Design Colors
        'tertiary-container': '#beab5e',
        'surface-container-low': '#f8f3ea',
        'surface-dim': '#ded9d1',
        'secondary-fixed': '#ffdf91',
        'on-tertiary': '#ffffff',
        'error-container': '#ffdad6',
        'surface-container': '#f2ede4',
        'surface-container-lowest': '#ffffff',
        'secondary': '#755b03',
        'on-tertiary-container': '#4b3f00',
        'inverse-primary': '#8bd894',
        'on-primary-container': '#d7ffd6',
        'surface-container-high': '#ece8df',
        'error': '#ba1a1a',
        'on-secondary': '#ffffff',
        'tertiary': '#6d5e18',
        'tertiary-fixed-dim': '#dac676',
        'tertiary-fixed': '#f7e28f',
        'secondary-container': '#fdd97b',
        'on-error': '#ffffff',
        'primary-container': '#347e44',
        'on-secondary-fixed-variant': '#594400',
        'background': '#fef9f0',
        'surface-container-highest': '#e7e2d9',
        'on-background': '#1d1c16',
        'inverse-surface': '#32302a',
        'on-tertiary-fixed-variant': '#534600',
        'surface-tint': '#206c34',
        'secondary-fixed-dim': '#e6c368',
        'primary-fixed-dim': '#8bd894',
        'on-secondary-fixed': '#241a00',
        'outline': '#707a6e',
        'on-primary': '#ffffff',
        'on-surface-variant': '#40493f',
        'on-primary-fixed-variant': '#005320',
        'on-primary-fixed': '#002109',
        'on-surface': '#1d1c16',
        'on-tertiary-fixed': '#221b00',
        'on-secondary-container': '#785d06',
        'outline-variant': '#bfc9bc',
        'inverse-on-surface': '#f5f0e7',
        'surface-bright': '#fef9f0',
        'primary-fixed': '#a7f5ae',
        'surface': '#fef9f0',
        'surface-variant': '#e7e2d9',
        'primary': '#16642e',
        'on-error-container': '#93000a',
        // Legacy aliases for backward compatibility
        'soft-linen': '#f2ede4',
        'ash-grey': '#abaf9f',
        'golden-bronze': '#be9e47',
        'olive': '#97863d',
        'fern': '#347e44',
        'fern-light': '#4a9a56',
        'fern-dark': '#2a5e35',
        'golden-bronze-light': '#d4b368',
        'soft-linen-dark': '#e5e0d5',
        'dark-fern': '#1a3d22',
        earth: '#347e44',
        leaf: '#347e44',
        'leaf-light': '#4a9a56',
        crop: '#be9e47',
        'crop-light': '#d4b368',
        cream: '#f2ede4',
        'cream-dark': '#e5e0d5',
        mist: '#f2ede4',
        charcoal: '#1a3d22',
        'text-muted': '#abaf9f',
      },
      fontFamily: {
        head: ['"DM Serif Display"', 'Georgia', 'serif'],
        body: ['"DM Sans"', 'sans-serif'],
      },
      borderRadius: {
        'xl': '10px',
      },
      transitionTimingFunction: {
        'custom': 'cubic-bezier(0.4, 0, 0.2, 1)',
      },
      transitionDuration: {
        '280': '280ms',
      },
    },
  },
  plugins: [],
}
