<?php
return array (
  0 => 
  array (
    'id' => 1,
    'seller_id' => 4,
    'title' => 'Premium White Maize - Grade A',
    'description' => 'High-quality white maize harvested this season. Perfect for human consumption and animal feed. Stored in proper conditions to maintain quality.',
    'price' => 0.2,
    'price_unit' => 'kg',
    'quantity' => 5000,
    'category' => 'grains',
    'location' => 'lilongwe',
    'image' => NULL,
    'status' => 'active',
    'created_at' => '2026-04-08 23:30:00',
    'updated_at' => '2026-04-08 23:30:00',
  ),
  1 => 
  array (
    'id' => 2,
    'seller_id' => 4,
    'title' => 'Organic Ground Nuts',
    'description' => 'Freshly harvested ground nuts, organically grown without pesticides. Excellent taste and high nutritional value.',
    'price' => 0.25,
    'price_unit' => 'kg',
    'quantity' => 1200,
    'category' => 'legumes',
    'location' => 'blantyre',
    'image' => NULL,
    'status' => 'active',
    'created_at' => '2026-04-08 23:31:00',
    'updated_at' => '2026-04-08 23:31:00',
  ),
  2 => 
  array (
    'id' => 3,
    'seller_id' => 4,
    'title' => 'High-Quality Soya Beans',
    'description' => 'Premium grade soya beans, high protein content. Perfect for making soy milk, tofu, and other soy products.',
    'price' => 0.38,
    'price_unit' => 'kg',
    'quantity' => 800,
    'category' => 'legumes',
    'location' => 'kasungu',
    'image' => NULL,
    'status' => 'active',
    'created_at' => '2026-04-08 23:32:00',
    'updated_at' => '2026-04-08 23:32:00',
  ),
  3 => 
  array (
    'id' => 4,
    'seller_id' => 4,
    'title' => 'Fresh Pigeon Peas',
    'description' => 'Locally grown pigeon peas, harvested at peak freshness. Great for traditional Malawian dishes.',
    'price' => 0.42,
    'price_unit' => 'kg',
    'quantity' => 2500,
    'category' => 'legumes',
    'location' => 'mzuzu',
    'image' => NULL,
    'status' => 'active',
    'created_at' => '2026-04-08 23:33:00',
    'updated_at' => '2026-04-08 23:33:00',
  ),
  4 => 
  array (
    'id' => 5,
    'seller_id' => 4,
    'title' => 'NPK Compound Fertilizer',
    'description' => 'Premium NPK fertilizer for optimal crop growth. Balanced nutrients for maximum yield.',
    'price' => 45,
    'price_unit' => 'bag',
    'quantity' => 200,
    'category' => 'inputs',
    'location' => 'lilongwe',
    'image' => NULL,
    'status' => 'active',
    'created_at' => '2026-04-08 23:34:00',
    'updated_at' => '2026-04-08 23:34:00',
  ),
  5 => 
  array (
    'id' => 6,
    'seller_id' => 6,
    'title' => 'uytuytuyt',
    'description' => 'uytuytiuytiuytiuyt',
    'price' => 1000.0,
    'price_unit' => 'bag',
    'quantity' => 500.0,
    'category' => 'grains',
    'location' => 'mangochi',
    'image' => 'uploads/products/product_69d6cf8f2803e2.73654676.jpg',
    'status' => 'active',
    'created_at' => '2026-04-08 23:58:39',
    'updated_at' => '2026-04-08 23:58:39',
  ),
  6 => 
  array (
    'id' => 7,
    'seller_id' => 6,
    'title' => 'Premium Maizw',
    'description' => 'High quality maize from the land down under',
    'price' => 50000.0,
    'price_unit' => 'bag',
    'quantity' => 500.0,
    'category' => 'grains',
    'location' => 'blantyre',
    'image' => 'uploads/products/product_69d6d056cfbbc2.90855899.jpg',
    'status' => 'active',
    'created_at' => '2026-04-09 00:01:58',
    'updated_at' => '2026-04-09 00:01:58',
  ),
  7 => 
  array (
    'id' => 8,
    'seller_id' => 6,
    'title' => 'beans',
    'description' => 'premium beans straight from the source',
    'price' => 20000.0,
    'price_unit' => 'bag',
    'quantity' => 20.0,
    'category' => 'grains',
    'location' => 'lilongwe',
    'image' => 'uploads/products/product_69d6d5f204f7f4.57918727.jpg',
    'status' => 'active',
    'created_at' => '2026-04-09 00:25:54',
    'updated_at' => '2026-04-09 00:25:54',
  ),
);
